@url = http://localhost:5249/conferences-module
@hostId = 8c780fdf-7694-4893-9ef0-c091fc447763

@conferenceId = 1577a6d9-2636-4558-9b53-32d9e214bba4

@accessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTgxZGQ0MC03ZWJlLTRjYzYtOGVkZC02ZDIzNzg1N2RlYjAiLCJ1bmlxdWVfbmFtZSI6IjExODFkZDQwLTdlYmUtNGNjNi04ZWRkLTZkMjM3ODU3ZGViMCIsImp0aSI6ImFmNzhiZWYyLTAwNDEtNDVkYi05YmRkLTBiZTY1NjUwODNjOSIsImlhdCI6IjE3Mzk5MTMwODg2MTUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTczOTkxMzA4OCwiZXhwIjoxNzM5OTQ5MDg4LCJpc3MiOiJjb25mYWIifQ.mULlQr9Bf-jNrX0n8l4nmI6UFj0r53HaQTdxAqGWu-Y

###
GET {{url}}

###
POST {{url}}/hosts
Content-Type: application/json

{
    "name": "Host #1",
    "description": "Lorem ipsum"
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Host #2"
}

###
DELETE {{url}}/hosts/{{hostId}}
Authorization: Bearer {{accessToken}}

###
POST {{url}}/conferences
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "Conference #1",
    "description": "Lorem ipsum",
    "location": "Test 123",
    "from": "2024-09-22",
    "to": "2024-09-24",
    "participantsLimit": 100,
    "logoUrl":null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "name": "Conference #2",
    "description": "Lorem ipsum",
    "location": "Test 123",
    "from": "2024-09-11",
    "to": "2024-09-15",
    "participantsLimit": 100,
    "logoUrl":null
}

###
DELETE {{url}}/conferences/{{conferenceId}}