@url = http://localhost:5249/conferences-module
@hostId = 8c780fdf-7694-4893-9ef0-c091fc447763

@conferenceId = 1577a6d9-2636-4558-9b53-32d9e214bba4

###
GET {{url}}

###
POST {{url}}/hosts
Content-Type: application/json

{
    "name": "Host #1",
    "description": "Lorem ipsum"
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{
    "name": "Host #2"
}

###
DELETE {{url}}/hosts/{{hostId}}

###
POST {{url}}/conferences
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "Conference #1",
    "description": "Lorem ipsum",
    "location": "Test 123",
    "from": "2024-09-22",
    "to": "2024-09-24",
    "participantsLimit": 100,
    "logoUrl":null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "name": "Conference #2",
    "description": "Lorem ipsum",
    "location": "Test 123",
    "from": "2024-09-11",
    "to": "2024-09-15",
    "participantsLimit": 100,
    "logoUrl":null
}

###
DELETE {{url}}/conferences/{{conferenceId}}